[package]
name = "sparse-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sparse-traits = {path = "../sparse-traits"}
mpi = "0.6.*"
